### ISSUE TITLE
occasional crash when building highways

### ISSUE THREAD

**Issue by ReadZead** [lambda-plugins/HighwayTools#24]
java.lang.NullPointerException: Unexpected error
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78750_j(PlayerControllerMP.java:373)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:346)
	at com.lambda.client.util.items.OperationKt.swapToSlot(Operation.kt:180)
	at com.lambda.client.util.items.OperationKt.swapToSlot(Operation.kt:171)
	at com.lambda.client.util.items.OperationKt.swapToBlock(Operation.kt:132)
	at com.lambda.client.util.items.OperationKt.swapToBlockOrMove(Operation.kt:45)
	at com.lambda.client.util.items.OperationKt.swapToBlockOrMove$default(Operation.kt:40)
	at trombone.handler.Player.swapOrMoveBlock(Player.kt:155)
	at trombone.handler.Tasks.doPlace(Tasks.kt:663)
	at trombone.handler.Tasks.doTask(Tasks.kt:384)
	at trombone.handler.Tasks.runTasks(Tasks.kt:212)
	at trombone.Trombone.tick(Trombone.kt:53)
	at HighwayTools._init_$lambda-65(HighwayTools.kt:173)
	at HighwayTools$$Lambda$1405/102221498.invoke(Unknown Source)
	at com.lambda.client.util.threads.ThreadSafetyKt.safeListener$lambda-1(ThreadSafety.kt:26)
	at com.lambda.client.util.threads.ThreadSafetyKt$$Lambda$396/228215717.invoke(Unknown Source)
	at com.lambda.client.event.LambdaEventBus.invokeSerial(LambdaEventBus.kt:49)
	at com.lambda.client.event.LambdaEventBus.postProfiler(LambdaEventBus.kt:37)
	at com.lambda.client.event.ForgeEventProcessor.onTick(ForgeEventProcessor.kt:38)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_57_ForgeEventProcessor_onTick_ClientTickEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.onPreClientTick(FMLCommonHandler.java:344)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1708)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by ReadZead** [comment]
never mind, it just wanted me to update optifine to the new preview version
